Fantom-foundation/opera-sfc

contracts/common/Initializable.sol, contracts/sfc/NetworkInitializer.sol, contracts/sfc/NodeDriver.sol, contracts/sfc/NodeInterface.sol, contracts/sfc/SFC.sol, contracts/test/UnitTestSFC.sol, test/SFC.js
- add fluid staking economy (stake lockups)
- decouple interaction with the node into the NodeDriver contract
- decouple genesis contract initialization into the NetworkInitializer contract
- rename methods stake -> delegate, unstake -> undelegate
- fix genesis state initialization
=> Fluid staking economy

contracts/sfc/LegacySfcWrapper.sol, contracts/sfc/NodeDriver.sol, contracts/sfc/SFC.sol, contracts/sfc/StakerConstants.sol, contracts/version/Version.sol, test/SFC.js
- add SFCv2 interface wrapper
- add restakeRewards method for backward compatibility with SFCv2 claim*CompoundRewards methods
- refactor early unlocking penalty tracking to allow future modifications
- SFC contract is upgradeable with copyCode method
=> Backward compatibility with 2.0.2

contracts/sfc/SFC.sol
If a staker calls unlockStake() for the full locked stake amount before the lock expires naturally, the amount staked is reduced to zero, but the original lock end time is still in place. This prevents a new lock to be placed since the isLockedUp() check still returns TRUE. The purpose of the PR is to allow such stakers to place a new lock before the previous lock timer expires naturally.
=> Fix stake lock check to include non-zero locked amount.

contracts/sfc/SFC.sol, contracts/version/Version.sol, package.json, test/SFC.js
- allow to refund slashed legacy delegations by an owner. The method is stateless
=> Refund slashed legacy delegations

contracts/sfc/SFC.sol, package.json, test/SFC.js
- erase refund slashed legacy delegations, as it was already used
=> Erase unused feunction

contracts/sfc/SFC.sol
Changed transfer to call to allow withdrawing funds and rewards to complex smartcontracts. Transfer has gas limit of 2300, which be insufficient when delegator consists of multiple proxies. Gas costs are covered by delegator, reentrancy protection is already present, so we can replace safely.
=> Change transfer to call to allow use by smarcontracts. 

contracts/sfc/SFC.sol
Reason: current behaviour blocks possibility to withdraw funds for validators, that already called claimRewards and was blocked (for example, for being offline) afterwards. Precisely, function unlockStake can not be called for such validator.
Calling unlockStake triggers _rawUndelegate(.., penalty), if stake of validator is less than minStake + penalty, this will not work. Also it is not possible to stake more funds to validator to work around this issue as validator is already deactivated.
=> Removed selfStakeAfterwards and DelegatedStakeLimit checks for inactive validators

contracts/sfc/SFCI.sol, contracts/sfc/SFCLib.sol, contracts/test/UnitTestSFC.sol
The method was previously used to transfer FTM from Ethereum ERC20 to Opera
=> Erase FTM minting

contracts/sfc/SFC.sol, contracts/sfc/SFCBase.sol, contracts/sfc/SFCLib.sol, contracts/sfc/SFCState.sol, contracts/test/UnitTestSFC.sol
Added documentation into SFCState comments, renamed few errors to be more descriptive.
Following fields, which are write-only for the SFC, only to be read from outside, removed:
* **totalSlashedStake** does not provide much useful information, it is even misleading - it includes only penalties subtracted from successful withdrawals. It does not contain slashed stake which was not withdrawn, or which even cannot be withdrawn because it is fully slashed.
* **EpochSnapshot.totalBaseRewardWeight** represents base (sum) for individual validators participation: `sum( stake * uptimeRatio ^ 2 )` However without individual baseRewardWeights, the number seems worthless. (baseRewardWeights are used in the BaseReward calculation, but not stored anywhere)
* **EpochSnapshot.totalTxRewardWeight** is the …
=> Remove unnecessary SFCState fields, errors rename

contracts/sfc/NodeDriver.sol, contracts/sfc/NodeDriverAuth.sol
Add documentation of NodeDriver/NodeDriverAuth public methods.
=> Add NodeDriver docs

contracts/interfaces/ISFC.sol, contracts/sfc/SFC.sol, test/SFC.ts
Add mapping from pubkey address (used by Bridge) to validator id.
This is necessary for the bridge integration.
The new mapping created as replacement of similar `pubkeyHashToValidatorID` (where the type prefix was included into the keccak256 hash)
=> Replace pubkeyHashToValidatorID by pubkeyAddressToValidatorID

contracts/interfaces/ISFC.sol, contracts/sfc/ConstantsManager.sol, contracts/sfc/NetworkInitializer.sol, contracts/sfc/SFC.sol, contracts/test/UnitTestSFC.sol, test/SFC.ts
* Updated and refactored version of #83
* Use Q1.30 number representation for the normalised uptime (fits into uint32)
* Used math [lemma for the average](https://docs.google.com/document/d/1kENdl4XBtBV7Zt7VmJ9Nvaq-gsinPrCbfog_CxtFHgI/)
* Used unsigned integers only to simplify checks/verification
* Disabled too inactive validators included but disabled by default. (I would prefer to include it into the audit.)
=> Add average uptime calculation

contracts/interfaces/ISFC.sol, contracts/sfc/SFC.sol
As discussed today, we may generalize votebook/governance interface to a generic stake changes subscriber.
Still not confirm if needed for the bridge, but maybe it can be considered an improvement even without it.
Removed external-callable recountVotes() instance, as it only potentially breaks the security model of the called contract. (If it is inteded to be called by user, the target contract should allow it directly.)
=> Generalize governance to stake changes subscriber

contracts/sfc/SFC.sol
This PR fixes resetting remainder to zero whenever the `averageUptime` exceeds `1e18` and is capped at `1e18`.
=> [OZ][L-01] Fix inaccurate uptime calculation due to remainder

contracts/interfaces/IStakeSubscriber.sol, contracts/sfc/SFC.sol
This PR replaces unsafe `abi.encodeWithSignature` with type safe `abi.encodeCall`.
=> [OZ][L-03] Unsafe ABI Encoding

contracts/sfc/NodeDriverAuth.sol
This PR replaces low-level assembly with high-level language constructs.
=> [OZ][N-13] Unnecessary Assembly Usage

contracts/sfc/NodeDriverAuth.sol, contracts/sfc/SFC.sol
This PR adds comments improvements including fixing typos.
=> [OZ][N-06] Comment Improvements

contracts/interfaces/ISFC.sol, contracts/sfc/SFC.sol, contracts/test/UnitTestSFC.sol, test/SFC.ts
This PR fixes inconsistent naming conventions to align best practices.
=> [OZ][N-08] Inconsistent Naming Convention for Functions and Variables

contracts/sfc/ConstantsManager.sol, contracts/sfc/NetworkInitializer.sol, contracts/test/UnitTestSFC.sol
This PR fixes inconsistent use of `Decimal.unit()` across the contracts.
=> [OZ][N-07] Inconsistent Use of Decimal.unit() and 1e18

contracts/sfc/SFC.sol
This PR replaces `transfer` call with `call` as it is not considered best practise.
=> [OZ][L-02] Transfer and send Calls Are No Longer Considered Best Practice
